### ISSUE TITLE
Artifact naming conflict when using screenly/cli@master action multiple times in same workflow

### ISSUE THREAD

**Issue by salmanfarisvp** [Screenly/cli#243]
### Issue Description
When using the `screenly/cli@master` GitHub Action multiple times within the same job/workflow, the second and subsequent uses fail with an artifact naming conflict error

#### Error Message

> Error: Failed to CreateArtifact: Received non-retryable error: Failed request: (409) Conflict: an artifact with this name already exists on the workflow run

### Expected Behavior
Each use of the `screenly/cli@master` action should create artifacts with unique names, or provide a parameter to control artifact naming, allowing multiple CLI commands to be executed within the same workflow without conflicts.

### Actual Behavior
The second use of the action fails because it attempts to create an artifact with the same name as the first use, resulting in a 409 Conflict error

### Steps to Reproduce

1. Create a GitHub Actions workflow with multiple steps using screenly/cli@master
2. Run different CLI commands in each step

> Note: The [official example in the repository](https://github.com/Screenly/cli/blob/master/.github/workflows/test-github-action.yml) only demonstrates a single use of the action, which is why this issue wasn't discovered during development.

#### Official Example (works fine ✅ - single use)

```
on:
  pull_request:
    branches:
      - master
jobs:
  test-github-action-workflow:
    runs-on: ubuntu-latest
    name: List screens
    steps:
      - uses: actions/checkout@v3
      - id: list-screens
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ secrets.SCREENLY_API_TOKEN }}
          cli_commands: screen list
```

Problematic Example (multiple uses ❌ - fails)

```
name: Screenly CLI Test

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment to list screens (stage or production)'
        required: true
        default: 'production'
        type: choice
        options:
          - stage
          - production

jobs:
  list-screens:
    name: List Screens from ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    env:
      SCREENLY_API_TOKEN: ${{ secrets.SCREENLY_API_TOKEN }}

    steps:
      - name: Run `screen list`
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: screen list

      - name: Run `edge-app list`
        uses: screenly/cli@master
        with:
          screenly_api_token: ${{ env.SCREENLY_API_TOKEN }}
          cli_commands: edge-app list

```

3. The first step (screen list) completes successfully
4. The second step (edge-app list) fails with the artifact conflict error

![Image](https://github.com/user-attachments/assets/2f6bc97c-733a-43f9-9417-3038738f1e7b)

### Suggested Solutions
1. Add artifact naming parameter: Allow users to specify custom artifact names
2. Auto-generate unique artifact names: Automatically append timestamps or step numbers to artifact names
3. Add option to disable artifacts: Allow users to disable artifact creation entirely
4. Use job/step context in artifact names: Automatically include job name, step name, or step index in artifact names to ensure uniqueness

**Comment by salmanfarisvp** [comment]
This is because, hardcoding the artifact name here at https://github.com/Screenly/cli/blob/master/action.yml Line 57. 

```
    - name: Upload artifacts of failed screenly cli command
      uses: actions/upload-artifact@v4
      with:
        name: run-cli-output
        path: |
          /tmp/screenly_cli_command_output.txt
```
